DROP TABLE IF EXISTS DAILY_TRANSACTIONS.ACCOUNT_TRANSACTIONS;
DROP TABLE IF EXISTS DAILY_TRANSACTIONS.ACCOUNT_NUMBERS;
DROP TABLE IF EXISTS DAILY_TRANSACTIONS.TRANSACTION_DESCRIPTIONS;

CREATE TABLE DAILY_TRANSACTIONS.ACCOUNT_NUMBERS(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
                                                ACCOUNT_NUMBER VARCHAR(4) NOT NULL,
                                                ACCOUNT_DESCRIPTION VARCHAR(255) NOT NULL);
ALTER TABLE DAILY_TRANSACTIONS.ACCOUNT_NUMBERS AUTO_INCREMENT = 1;

CREATE TABLE DAILY_TRANSACTIONS.TRANSACTION_DESCRIPTIONS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                                                         TRANSACTION_DESCRIPTION VARCHAR(255) NOT NULL,
                                                         UNIQUE(TRANSACTION_DESCRIPTION));
ALTER TABLE DAILY_TRANSACTIONS.TRANSACTION_DESCRIPTIONS AUTO_INCREMENT = 1;


CREATE TABLE DAILY_TRANSACTIONS.ACCOUNT_TRANSACTIONS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                                                     TRANSACTION_TIMESTAMP TIMESTAMP NOT NULL,
                                                     TRANSACTION_AMOUNT DECIMAL(12,2) NOT NULL,
                                                     TRANSACTION_ACCOUNT_ID INTEGER NOT NULL,
                                                     TRANSACTION_DESCRIPTION_ID BIGINT NOT NULL,
                                                     FOREIGN KEY (TRANSACTION_ACCOUNT_ID)
                                                     REFERENCES DAILY_TRANSACTIONS.ACCOUNT_NUMBERS(ID),
                                                     FOREIGN KEY (TRANSACTION_DESCRIPTION_ID)
                                                     REFERENCES DAILY_TRANSACTIONS.TRANSACTION_DESCRIPTIONS(ID));
ALTER TABLE DAILY_TRANSACTIONS.ACCOUNT_TRANSACTIONS AUTO_INCREMENT = 1;

INSERT INTO DAILY_TRANSACTIONS.ACCOUNT_NUMBERS VALUES(1,'0945','UCU VISA DEBIT');
INSERT INTO DAILY_TRANSACTIONS.ACCOUNT_NUMBERS VALUES(2,'5444','BBT DEBIT');
INSERT INTO DAILY_TRANSACTIONS.ACCOUNT_NUMBERS VALUES(3,'3345','UCU VISA DEBIT');
INSERT INTO DAILY_TRANSACTIONS.ACCOUNT_NUMBERS VALUES(4,'4552','UCU VISA CREDIT');
INSERT INTO DAILY_TRANSACTIONS.ACCOUNT_NUMBERS VALUES(5,'9945','GM CARD');
INSERT INTO DAILY_TRANSACTIONS.ACCOUNT_NUMBERS VALUES(6,'0318','LENS CRAFTERS');
INSERT INTO DAILY_TRANSACTIONS.ACCOUNT_NUMBERS VALUES(7,'4810','UCU CHECKING');
INSERT INTO DAILY_TRANSACTIONS.ACCOUNT_NUMBERS VALUES(8,'4480','UCU VISA CREDIT');

SHOW TABLES FROM DAILY_TRANSACTIONS;

SHOW COLUMNS FROM DAILY_TRANSACTIONS.ACCOUNT_NUMBERS;
SHOW COLUMNS FROM DAILY_TRANSACTIONS.ACCOUNT_TRANSACTIONS;
SHOW COLUMNS FROM DAILY_TRANSACTIONS.TRANSACTION_DESCRIPTIONS;

SELECT * FROM DAILY_TRANSACTIONS.ACCOUNT_NUMBERS;
